name: Clone and Push Magento2 to new branch

on:
  workflow_dispatch

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone Magento 2 repository
        run: |
          git clone --depth 1 https://github.com/magento/magento2.git magento
          cp -r magento/* .
          rm -rf magento

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Imported Magento 2 source code"
          branch: magento-import
