name: Clone and Push Magento2 to new branch

on:
  workflow_dispatch

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Loofy147"
          git config --global user.email "ebh.ceo213@gmail.com"

      - name: Clone Magento 2 repository
        run: |
          git clone --depth 1 https://github.com/magento/magento2.git magento
          cp -r magento/* .
          rm -rf magento

      - name: Create new branch and commit changes
        run: |
          git checkout -b magento-import
          git add .
          git commit -m "Imported Magento 2"
          git push origin magento-import
